/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Nikho Sagala
 */
public class HomeAdmin extends javax.swing.JFrame {

    /**
     * Creates new form HomeAdmin
     */
    public HomeAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnKelolaMobil = new javax.swing.JButton();
        btnKelolaPemesanan = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnTransaksi = new javax.swing.JButton();
        btnReport = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        pic_rentalmobil1 = new javax.swing.JLabel();
        pic_mobil1 = new javax.swing.JLabel();
        btnKelolaPengembalian = new javax.swing.JButton();
        btnKelolaMobil1 = new javax.swing.JButton();
        btnKelolaPemesanan1 = new javax.swing.JButton();
        btnLogout1 = new javax.swing.JButton();
        btnTransaksi1 = new javax.swing.JButton();
        btnReport1 = new javax.swing.JButton();
        btnExit1 = new javax.swing.JButton();
        pic_rentalmobil2 = new javax.swing.JLabel();
        pic_mobil2 = new javax.swing.JLabel();
        btnKelolaPengembalian1 = new javax.swing.JButton();
        bg_white1 = new javax.swing.JPanel();
        btnLogout2 = new javax.swing.JButton();
        btnTransaksi2 = new javax.swing.JButton();
        btnReport2 = new javax.swing.JButton();
        btnExit2 = new javax.swing.JButton();
        pic_rentalmobil3 = new javax.swing.JLabel();
        pic_mobil3 = new javax.swing.JLabel();
        btnKelolaSupir = new javax.swing.JButton();
        btnKelolaMobil2 = new javax.swing.JButton();

        btnKelolaMobil.setBackground(new java.awt.Color(255, 255, 255));
        btnKelolaMobil.setIcon(new javax.swing.ImageIcon("D:\\Documents\\NetBeansProjects\\RPL-TBO-branch\\src\\assets\\add_mobil.png")); // NOI18N
        btnKelolaMobil.setText("Kelola Mobil");
        btnKelolaMobil.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnKelolaMobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKelolaMobilActionPerformed(evt);
            }
        });

        btnKelolaPemesanan.setBackground(new java.awt.Color(255, 255, 255));
        btnKelolaPemesanan.setIcon(new javax.swing.ImageIcon("D:\\Documents\\NetBeansProjects\\RPL-TBO-branch\\src\\assets\\pinjam.png")); // NOI18N
        btnKelolaPemesanan.setText("Kelola Pemesanan");
        btnKelolaPemesanan.setToolTipText("");
        btnKelolaPemesanan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnKelolaPemesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKelolaPemesananActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(255, 255, 255));
        btnLogout.setIcon(new javax.swing.ImageIcon("D:\\Documents\\NetBeansProjects\\RPL-TBO-branch\\src\\assets\\loginoke.png")); // NOI18N
        btnLogout.setText("Log Out");
        btnLogout.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnTransaksi.setBackground(new java.awt.Color(255, 255, 255));
        btnTransaksi.setIcon(new javax.swing.ImageIcon("D:\\Documents\\NetBeansProjects\\RPL-TBO-branch\\src\\assets\\transaksi.png")); // NOI18N
        btnTransaksi.setText("Transaksi");
        btnTransaksi.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransaksiActionPerformed(evt);
            }
        });

        btnReport.setBackground(new java.awt.Color(255, 255, 255));
        btnReport.setIcon(new javax.swing.ImageIcon("D:\\Documents\\NetBeansProjects\\RPL-TBO-branch\\src\\assets\\printer.png")); // NOI18N
        btnReport.setText("Report");
        btnReport.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(255, 255, 255));
        btnExit.setIcon(new javax.swing.ImageIcon("D:\\Documents\\NetBeansProjects\\RPL-TBO-branch\\src\\assets\\Exit1.jpg")); // NOI18N
        btnExit.setText("Exit");
        btnExit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        pic_rentalmobil1.setIcon(new javax.swing.ImageIcon("D:\\Documents\\NetBeansProjects\\RPL-TBO-branch\\src\\assets\\Rental Mobil.jpg")); // NOI18N

        pic_mobil1.setIcon(new javax.swing.ImageIcon("D:\\Documents\\NetBeansProjects\\RPL-TBO-branch\\src\\assets\\Background.png")); // NOI18N
        pic_mobil1.setText("jLabel2");

        btnKelolaPengembalian.setBackground(new java.awt.Color(255, 255, 255));
        btnKelolaPengembalian.setIcon(new javax.swing.ImageIcon("D:\\Documents\\NetBeansProjects\\RPL-TBO-branch\\src\\assets\\kembali_mobil.png")); // NOI18N
        btnKelolaPengembalian.setText("Kelola Pengembalian");
        btnKelolaPengembalian.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnKelolaPengembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKelolaPengembalianActionPerformed(evt);
            }
        });

        btnKelolaMobil1.setBackground(new java.awt.Color(255, 255, 255));
        btnKelolaMobil1.setIcon(new javax.swing.ImageIcon("D:\\Documents\\NetBeansProjects\\RPL-TBO-branch\\src\\assets\\add_mobil.png")); // NOI18N
        btnKelolaMobil1.setText("Kelola Mobil");
        btnKelolaMobil1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnKelolaMobil1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKelolaMobil1ActionPerformed(evt);
            }
        });

        btnKelolaPemesanan1.setBackground(new java.awt.Color(255, 255, 255));
        btnKelolaPemesanan1.setIcon(new javax.swing.ImageIcon("D:\\Documents\\NetBeansProjects\\RPL-TBO-branch\\src\\assets\\pinjam.png")); // NOI18N
        btnKelolaPemesanan1.setText("Kelola Pemesanan");
        btnKelolaPemesanan1.setToolTipText("");
        btnKelolaPemesanan1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnKelolaPemesanan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKelolaPemesanan1ActionPerformed(evt);
            }
        });

        btnLogout1.setBackground(new java.awt.Color(255, 255, 255));
        btnLogout1.setIcon(new javax.swing.ImageIcon("D:\\Documents\\NetBeansProjects\\RPL-TBO-branch\\src\\assets\\loginoke.png")); // NOI18N
        btnLogout1.setText("Log Out");
        btnLogout1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLogout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogout1ActionPerformed(evt);
            }
        });

        btnTransaksi1.setBackground(new java.awt.Color(255, 255, 255));
        btnTransaksi1.setIcon(new javax.swing.ImageIcon("D:\\Documents\\NetBeansProjects\\RPL-TBO-branch\\src\\assets\\transaksi.png")); // NOI18N
        btnTransaksi1.setText("Transaksi");
        btnTransaksi1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTransaksi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransaksi1ActionPerformed(evt);
            }
        });

        btnReport1.setBackground(new java.awt.Color(255, 255, 255));
        btnReport1.setIcon(new javax.swing.ImageIcon("D:\\Documents\\NetBeansProjects\\RPL-TBO-branch\\src\\assets\\printer.png")); // NOI18N
        btnReport1.setText("Report");
        btnReport1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnReport1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReport1ActionPerformed(evt);
            }
        });

        btnExit1.setBackground(new java.awt.Color(255, 255, 255));
        btnExit1.setIcon(new javax.swing.ImageIcon("D:\\Documents\\NetBeansProjects\\RPL-TBO-branch\\src\\assets\\Exit1.jpg")); // NOI18N
        btnExit1.setText("Exit");
        btnExit1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnExit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExit1ActionPerformed(evt);
            }
        });

        pic_rentalmobil2.setIcon(new javax.swing.ImageIcon("D:\\Documents\\NetBeansProjects\\RPL-TBO-branch\\src\\assets\\Rental Mobil.jpg")); // NOI18N

        pic_mobil2.setIcon(new javax.swing.ImageIcon("D:\\Documents\\NetBeansProjects\\RPL-TBO-branch\\src\\assets\\Background.png")); // NOI18N
        pic_mobil2.setText("jLabel2");

        btnKelolaPengembalian1.setBackground(new java.awt.Color(255, 255, 255));
        btnKelolaPengembalian1.setIcon(new javax.swing.ImageIcon("D:\\Documents\\NetBeansProjects\\RPL-TBO-branch\\src\\assets\\kembali_mobil.png")); // NOI18N
        btnKelolaPengembalian1.setText("Kelola Pengembalian");
        btnKelolaPengembalian1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnKelolaPengembalian1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKelolaPengembalian1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg_white1.setBackground(new java.awt.Color(255, 255, 255));
        bg_white1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        bg_white1.setPreferredSize(new java.awt.Dimension(950, 610));

        btnLogout2.setBackground(new java.awt.Color(255, 255, 255));
        btnLogout2.setIcon(new javax.swing.ImageIcon("D:\\Documents\\NetBeansProjects\\RPL-TBO-branch\\src\\assets\\loginoke.png")); // NOI18N
        btnLogout2.setText("Log Out");
        btnLogout2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLogout2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogout2ActionPerformed(evt);
            }
        });

        btnTransaksi2.setBackground(new java.awt.Color(255, 255, 255));
        btnTransaksi2.setIcon(new javax.swing.ImageIcon("D:\\Documents\\NetBeansProjects\\RPL-TBO-branch\\src\\assets\\transaksi.png")); // NOI18N
        btnTransaksi2.setText("Transaksi");
        btnTransaksi2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTransaksi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransaksi2ActionPerformed(evt);
            }
        });

        btnReport2.setBackground(new java.awt.Color(255, 255, 255));
        btnReport2.setIcon(new javax.swing.ImageIcon("D:\\Documents\\NetBeansProjects\\RPL-TBO-branch\\src\\assets\\printer.png")); // NOI18N
        btnReport2.setText("Report");
        btnReport2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnReport2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReport2ActionPerformed(evt);
            }
        });

        btnExit2.setBackground(new java.awt.Color(255, 255, 255));
        btnExit2.setIcon(new javax.swing.ImageIcon("D:\\Documents\\NetBeansProjects\\RPL-TBO-branch\\src\\assets\\Exit1.jpg")); // NOI18N
        btnExit2.setText("Exit");
        btnExit2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnExit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExit2ActionPerformed(evt);
            }
        });

        pic_rentalmobil3.setIcon(new javax.swing.ImageIcon("D:\\Documents\\NetBeansProjects\\RPL-TBO-branch\\src\\assets\\Rental Mobil.jpg")); // NOI18N

        pic_mobil3.setIcon(new javax.swing.ImageIcon("D:\\Documents\\NetBeansProjects\\RPL-TBO-branch\\src\\assets\\Background.png")); // NOI18N
        pic_mobil3.setText("jLabel2");

        btnKelolaSupir.setBackground(new java.awt.Color(255, 255, 255));
        btnKelolaSupir.setIcon(new javax.swing.ImageIcon("D:\\Documents\\NetBeansProjects\\Rental Mobil\\src\\assets\\user_iconn.png")); // NOI18N
        btnKelolaSupir.setText("Kelola Supir");
        btnKelolaSupir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnKelolaSupir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKelolaSupirActionPerformed(evt);
            }
        });

        btnKelolaMobil2.setBackground(new java.awt.Color(255, 255, 255));
        btnKelolaMobil2.setIcon(new javax.swing.ImageIcon("D:\\Documents\\NetBeansProjects\\RPL-TBO-branch\\src\\assets\\add_mobil.png")); // NOI18N
        btnKelolaMobil2.setText("Kelola Mobil");
        btnKelolaMobil2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnKelolaMobil2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKelolaMobil2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bg_white1Layout = new javax.swing.GroupLayout(bg_white1);
        bg_white1.setLayout(bg_white1Layout);
        bg_white1Layout.setHorizontalGroup(
            bg_white1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_white1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(bg_white1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bg_white1Layout.createSequentialGroup()
                        .addGap(340, 340, 340)
                        .addComponent(pic_rentalmobil3, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bg_white1Layout.createSequentialGroup()
                        .addGroup(bg_white1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bg_white1Layout.createSequentialGroup()
                                .addGroup(bg_white1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnKelolaSupir, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnTransaksi2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnReport2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnExit2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg_white1Layout.createSequentialGroup()
                                .addGroup(bg_white1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnLogout2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnKelolaMobil2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)))
                        .addComponent(pic_mobil3, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        bg_white1Layout.setVerticalGroup(
            bg_white1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_white1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(pic_rentalmobil3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(pic_mobil3, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(bg_white1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(btnLogout2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnKelolaMobil2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnKelolaSupir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnTransaksi2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnReport2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnExit2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 950, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(bg_white1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(bg_white1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKelolaMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelolaMobilActionPerformed
        // TODO add your handling code here:
        this.hide();
        bg_white1.removeAll();
        KelolaMobil km = new KelolaMobil();
        km.setVisible(true);
        bg_white1.add(km);
    }//GEN-LAST:event_btnKelolaMobilActionPerformed

    private void btnKelolaPemesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelolaPemesananActionPerformed
        // TODO add your handling code here:
        this.hide();
        bg_white1.removeAll();
        KelolaPemesanan kp = new KelolaPemesanan();
        kp.setVisible(true);
        bg_white1.add(kp);
    }//GEN-LAST:event_btnKelolaPemesananActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        dispose();
        Login Lg = new Login();
        Lg.setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransaksiActionPerformed
        // TODO add your handling code here:
        this.hide();
        bg_white1.removeAll();
        Transaksi Tr = new Transaksi();
        Tr.setVisible(true);
        bg_white1.add(Tr);
    }//GEN-LAST:event_btnTransaksiActionPerformed

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
        // TODO add your handling code here:
        this.hide();
        Report Rp = new Report();
        Rp.show();
    }//GEN-LAST:event_btnReportActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnKelolaPengembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelolaPengembalianActionPerformed
        // TODO add your handling code here:
        this.hide();
        bg_white1.removeAll();
        KelolaPengembalian kpe = new KelolaPengembalian();
        kpe.setVisible(true);
        bg_white1.add(kpe);
    }//GEN-LAST:event_btnKelolaPengembalianActionPerformed

    private void btnKelolaMobil1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelolaMobil1ActionPerformed
        // TODO add your handling code here:
        this.hide();
        bg_white1.removeAll();
        KelolaMobil km = new KelolaMobil();
        km.setVisible(true);
        bg_white1.add(km);
    }//GEN-LAST:event_btnKelolaMobil1ActionPerformed

    private void btnKelolaPemesanan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelolaPemesanan1ActionPerformed
        // TODO add your handling code here:
        this.hide();
        bg_white1.removeAll();
        KelolaPemesanan kp = new KelolaPemesanan();
        kp.setVisible(true);
        bg_white1.add(kp);
    }//GEN-LAST:event_btnKelolaPemesanan1ActionPerformed

    private void btnLogout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogout1ActionPerformed
        // TODO add your handling code here:
        dispose();
        Login Lg = new Login();
        Lg.setVisible(true);
    }//GEN-LAST:event_btnLogout1ActionPerformed

    private void btnTransaksi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransaksi1ActionPerformed
        // TODO add your handling code here:
        this.hide();
        bg_white1.removeAll();
        Transaksi Tr = new Transaksi();
        Tr.setVisible(true);
        bg_white1.add(Tr);
    }//GEN-LAST:event_btnTransaksi1ActionPerformed

    private void btnReport1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReport1ActionPerformed
        // TODO add your handling code here:
        this.hide();
        Report Rp = new Report();
        Rp.show();
    }//GEN-LAST:event_btnReport1ActionPerformed

    private void btnExit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExit1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExit1ActionPerformed

    private void btnKelolaPengembalian1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelolaPengembalian1ActionPerformed
        // TODO add your handling code here:
        this.hide();
        bg_white1.removeAll();
        KelolaPengembalian kpe = new KelolaPengembalian();
        kpe.setVisible(true);
        bg_white1.add(kpe);
    }//GEN-LAST:event_btnKelolaPengembalian1ActionPerformed

    private void btnLogout2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogout2ActionPerformed
        // TODO add your handling code here:
        dispose();
        Login Lg = new Login();
        Lg.setVisible(true);
    }//GEN-LAST:event_btnLogout2ActionPerformed

    private void btnTransaksi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransaksi2ActionPerformed
        // TODO add your handling code here:
        this.hide();
        bg_white1.removeAll();
        Transaksi Tr = new Transaksi();
        Tr.setVisible(true);
        bg_white1.add(Tr);
    }//GEN-LAST:event_btnTransaksi2ActionPerformed

    private void btnReport2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReport2ActionPerformed
        // TODO add your handling code here:
        this.hide();
        Report Rp = new Report();
        Rp.show();
    }//GEN-LAST:event_btnReport2ActionPerformed

    private void btnExit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExit2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExit2ActionPerformed

    private void btnKelolaSupirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelolaSupirActionPerformed
        // TODO add your handling code here:
        this.hide();
        bg_white1.removeAll();
        KelolaSupir kpe = new KelolaSupir();
        kpe.setVisible(true);
        bg_white1.add(kpe);
    }//GEN-LAST:event_btnKelolaSupirActionPerformed

    private void btnKelolaMobil2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelolaMobil2ActionPerformed
        // TODO add your handling code here:
        this.hide();
        bg_white1.removeAll();
        KelolaMobil km = new KelolaMobil();
        km.setVisible(true);
        bg_white1.add(km);
    }//GEN-LAST:event_btnKelolaMobil2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg_white1;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnExit1;
    private javax.swing.JButton btnExit2;
    private javax.swing.JButton btnKelolaMobil;
    private javax.swing.JButton btnKelolaMobil1;
    private javax.swing.JButton btnKelolaMobil2;
    private javax.swing.JButton btnKelolaPemesanan;
    private javax.swing.JButton btnKelolaPemesanan1;
    private javax.swing.JButton btnKelolaPengembalian;
    private javax.swing.JButton btnKelolaPengembalian1;
    private javax.swing.JButton btnKelolaSupir;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnLogout1;
    private javax.swing.JButton btnLogout2;
    private javax.swing.JButton btnReport;
    private javax.swing.JButton btnReport1;
    private javax.swing.JButton btnReport2;
    private javax.swing.JButton btnTransaksi;
    private javax.swing.JButton btnTransaksi1;
    private javax.swing.JButton btnTransaksi2;
    private javax.swing.JLabel pic_mobil1;
    private javax.swing.JLabel pic_mobil2;
    private javax.swing.JLabel pic_mobil3;
    private javax.swing.JLabel pic_rentalmobil1;
    private javax.swing.JLabel pic_rentalmobil2;
    private javax.swing.JLabel pic_rentalmobil3;
    // End of variables declaration//GEN-END:variables
}
