/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.*;
import Model.*;
import java.util.List;

/**
 *
 * @author gggggggggggggggggggg
 */
public class KelolaPengembalian extends javax.swing.JFrame {

    /**
     * Creates new form Kelolapengembalian
     */
    public KelolaPengembalian() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_white = new javax.swing.JPanel();
        pic_kelolapengembalian = new javax.swing.JLabel();
        lbl_datamobil = new javax.swing.JLabel();
        lbl_nopolisi = new javax.swing.JLabel();
        txtKTP = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btn_kembalikanmobil = new javax.swing.JButton();
        btn_home = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg_white.setBackground(new java.awt.Color(255, 255, 255));

        lbl_datamobil.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lbl_datamobil.setText("PENGEMBALIAN");

        lbl_nopolisi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_nopolisi.setText("NO KTP Pemesan");

        txtKTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKTPActionPerformed(evt);
            }
        });

        btn_kembalikanmobil.setBackground(new java.awt.Color(255, 255, 255));
        btn_kembalikanmobil.setText("Kembalkan Mobil");
        btn_kembalikanmobil.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_kembalikanmobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kembalikanmobilActionPerformed(evt);
            }
        });

        btn_home.setBackground(new java.awt.Color(255, 255, 255));
        btn_home.setText("Home");
        btn_home.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_homeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bg_whiteLayout = new javax.swing.GroupLayout(bg_white);
        bg_white.setLayout(bg_whiteLayout);
        bg_whiteLayout.setHorizontalGroup(
            bg_whiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_whiteLayout.createSequentialGroup()
                .addGroup(bg_whiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bg_whiteLayout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(bg_whiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pic_kelolapengembalian)
                            .addComponent(jLabel3)))
                    .addGroup(bg_whiteLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(lbl_datamobil))
                    .addGroup(bg_whiteLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(lbl_nopolisi)
                        .addGap(93, 93, 93)
                        .addComponent(txtKTP, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(196, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg_whiteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_home, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_kembalikanmobil, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        bg_whiteLayout.setVerticalGroup(
            bg_whiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_whiteLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(bg_whiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pic_kelolapengembalian)
                    .addComponent(jLabel1))
                .addGroup(bg_whiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bg_whiteLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel3))
                    .addGroup(bg_whiteLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_datamobil)))
                .addGap(60, 60, 60)
                .addGroup(bg_whiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKTP, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_nopolisi))
                .addGap(141, 141, 141)
                .addGroup(bg_whiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_home, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_kembalikanmobil, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(bg_white, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg_white, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_homeActionPerformed
    this.dispose();
    Home a = new Home();
    a.show();  // TODO add your handling code here:
    }//GEN-LAST:event_btn_homeActionPerformed

    private void txtKTPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKTPActionPerformed
                        // TODO add your handling code here:
    }//GEN-LAST:event_txtKTPActionPerformed

    private void btn_kembalikanmobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kembalikanmobilActionPerformed
        String noktp = txtKTP.getText();
        Supir s = new Supir();
        Mobil m = new Mobil();
        ConMobil cm = new ConMobil();
        ConSupir cs = new ConSupir();
        ConPemesan cp = new ConPemesan();
        List<Pemesan> lp = cp.getPemesananbyID(noktp);
        String plat = lp.get(0).getPlat();
        int idSupir = lp.get(0).getidSupir();
        cm.updateStatMobilkembali(plat);
        if(idSupir != 0){
        s.setIdSupir(idSupir);
        s.setStatus(false);
        cs.updateSupirSQL(s);
        }
        
// TODO add your handling code here:
    }//GEN-LAST:event_btn_kembalikanmobilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KelolaPengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KelolaPengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KelolaPengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KelolaPengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KelolaPengembalian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg_white;
    private javax.swing.JButton btn_home;
    private javax.swing.JButton btn_kembalikanmobil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbl_datamobil;
    private javax.swing.JLabel lbl_nopolisi;
    private javax.swing.JLabel pic_kelolapengembalian;
    private javax.swing.JTextField txtKTP;
    // End of variables declaration//GEN-END:variables
}
